# Custom Language File for Launcher Customizer

[ejs.app]
title = "TSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Redllamaaa/tsmplauncher"
mediaTwitterURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/Redllamaaa/tsmplauncher"
supportLink = "https://github.com/Redllamaaa/tsmplauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO TOTEM CLUB"
welcomeDescription = "Our pirate crew is out to sea on a expedition; Death Hill. On their way there, they find a certain someone in the sea, and decide to let her on board. The crew takes her with them to Death Hill, and together, they all look for the treasure! "
welcomeDescCTA = "You are just a few clicks away from this adventure, on DEATH HILL."