# Custom Language File for Launcher Customizer

[ejs.app]
title = "TSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://docs.google.com/presentation/d/1bNUP5qS1UGcLbBEk-_zFv1gntsSxlF3k9ceCX51iU3g/edit"
mediaTwitterURL = "https://twitter.com/TotemClub2"
mediaDiscordURL = "https://discord.gg/fVe3xGj7qY"

[ejs.settings]
sourceGithubLink = "https://github.com/Redllamaaa/tsmplauncher"
supportLink = "https://github.com/Redllamaaa/tsmplauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO TOTEM CLUB"
welcomeDescription = "Our pirate crew is out to sea on a expedition; Death Hill. On their way there, they find a certain someone in the sea, and decide to let her on board. The crew takes her with them to Death Hill, and together, they all look for the treasure! "
welcomeDescCTA = "You are just a few clicks away from this adventure."
